/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

@interface BluetoothDevice : NSObject
{
    struct BTDeviceImpl *_device;
    int _batteryLevel;
    BOOL _supportsBatteryLevel;
}

- (void)_setBatteryLevel:(int)fp8;	// IMP=0x3227030c
- (id)address;	// IMP=0x32270000
- (BOOL)available;	// IMP=0x32270324
- (int)batteryLevel;	// IMP=0x322702f8
- (int)compare:(id)fp8;	// IMP=0x322702a0
- (void)connect;	// IMP=0x3227018c
- (BOOL)connected;	// IMP=0x3227013c
- (struct BTDeviceImpl *)device;	// IMP=0x3226ff4c
- (void)disconnect;	// IMP=0x32270254
- (id)initWithDevice:(struct BTDeviceImpl *)fp8;	// IMP=0x3226fee8
- (id)name;	// IMP=0x3226ff64
- (BOOL)paired;	// IMP=0x322700ec
- (void)setDevice:(struct BTDeviceImpl *)fp8;	// IMP=0x3226ff54
- (void)setPIN:(id)fp8;	// IMP=0x322701cc
- (BOOL)supported;	// IMP=0x32270080
- (BOOL)supportsBatteryLevel;	// IMP=0x3227031c
- (int)type;	// IMP=0x32270050
- (void)unpair;	// IMP=0x32270214

@end

